import type { RequestHandler } from './$types';
import transitLines from '../../../data/generated/transit-lines.json';

/**
 * Served as a route rather than a static asset so the railway overlay stays out of
 * the page's own payload: the map component only requests it the first time
 * someone actually switches the overlay on.
 *
 * The data is regenerated by `bun run sources:transit`, which is far coarser than
 * this, so the response is cacheable for a long time.
 */
export const GET: RequestHandler = () =>
	new Response(JSON.stringify(transitLines), {
		headers: {
			'content-type': 'application/json; charset=utf-8',
			'cache-control': 'public, max-age=86400'
		}
	});
